apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Source repository
  source:
    repoURL: https://github.com/arup07/node-demo-app-manifests.git
    targetRevision: main
    path: .
  
  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true        # Automatically delete resources that are no longer in Git
      selfHeal: true     # Automatically sync when cluster state differs from Git
      allowEmpty: false  # Don't sync if the repo is empty
    syncOptions:
      - CreateNamespace=true  # Create namespace if it doesn't exist
      - PruneLast=true        # Prune resources last
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences in certain fields
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore if HPA is managing replicas

