apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-demo-app
  namespace: default
  labels:
    app: node-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-demo-app
  template:
    metadata:
      labels:
        app: node-demo-app
    spec:
      containers:
      - name: node-demo-app
        image: arup07/node-demo-app:7
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: node-demo-app-config
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: node-demo-app-config
              key: db_port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: node-demo-app-config
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: node-demo-app-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: node-demo-app-secret
              key: db_password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

