apiVersion: v1
kind: Service
metadata:
  name: node-demo-app-service
  namespace: default
  labels:
    app: node-demo-app
spec:
  type: LoadBalancer
  selector:
    app: node-demo-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None

